title = "Yu-Sheng Lee"
baseURL = "https://yushglee.github.io/"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
math = true          # enable KaTeX (https://katex.org/) globally

[services]
  [services.googleAnalytics]
    id = ""  # add your tracking id

[params]
  author = "Yu-Sheng Lee"
  description = "Personal website of Yu-Sheng Lee with research, teaching, and contact information."
  favicon = true
  [params.style]
   pageWidth = "900px"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Research"
    url = "/research"
    weight = 2
  [[menu.main]]
    name = "Teaching"
    url = "/teaching"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
